//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoUploaderWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoInformation
    {
        public int VideoID { get; set; }
        public int UserID { get; set; }
        public string VideoTitle { get; set; }
        public string About { get; set; }
        public string Tags { get; set; }
        public string Language { get; set; }
        public string Category { get; set; }
        public string VideoLocation { get; set; }
        public string UploadedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
